version: "3.9"
services:

  rabbitmq:
    image: docker.arvancloud.ir/rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword  

  oracle-db:
    image: docker.arvancloud.ir/gvenzl/oracle-free:23.4-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=1234
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./db-init:/docker-entrypoint-initdb.d 


volumes:
  oracle-data:
