version: "3.9"
services:

  rabbitmq:
    image: docker.arvancloud.ir/rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword  

  oracle-db:
    image: docker.arvancloud.ir/gvenzl/oracle-free:23.4-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=1234
    volumes:
      - oracle-data:/opt/oracle/oradata

  transaction-service:
    build:
      context: ./TransactionService
      dockerfile: Dockerfile   # optional if file is named Dockerfile
    container_name: transaction-service
    ports:
      - "8081:8080"  # map host port 8081 to container's 8080
    depends_on:
      - rabbitmq
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: myuser
      SPRING_RABBITMQ_PASSWORD: mypassword

  customer-service:
    build:
      context: ./CustomerService
      dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "8082:8080"  # map host port 8082 to container's 8080
    depends_on:
      - rabbitmq
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: myuser
      SPRING_RABBITMQ_PASSWORD: mypassword

volumes:
  oracle-data:
